language: java
jdk:
  - openjdk17

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ./gradlew jlinkZip jpackage shadowJar
      zip -r astre-jdk$TRAVIS_OS_NAME-zip build/distributions/astre-image.zip
      zip -r astre-jdk$TRAVIS_OS_NAME-jar build/libs/*.jar
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./gradlew jlinkZip jpackage shadowJar
      zip -r astre-jdk$TRAVIS_OS_NAME-zip build/distributions/astre-image.zip
      zip -r astre-jdk$TRAVIS_OS_NAME-jar build/libs/*.jar
      zip -r astre-jdk$TRAVIS_OS_NAME-dmg build/jpackage/*.dmg
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
      ./gradlew jlinkZip jpackage shadowJar
      zip -r astre-jdk$TRAVIS_OS_NAME-zip build/distributions/astre-image.zip
      zip -r astre-jdk$TRAVIS_OS_NAME-jar build/libs/*.jar
      zip -r astre-jdk$TRAVIS_OS_NAME-exe build/jpackage/*.exe
      zip -r astre-jdk$TRAVIS_OS_NAME-msi build/jpackage/*.msi
    fi

before_deploy:
  - mv astre-jdk$TRAVIS_OS_NAME-zip astre-jdk$TRAVIS_OS_NAME-jar build/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "astre-jdk$TRAVIS_OS_NAME-*"
  skip_cleanup: true
  on:
    tags: true
