# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '17.0.6' ]
      fail-fast: false

    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Execute build
      run: ./gradlew --info --stacktrace build
    - name: Execute jlink
      run: ./gradlew --info --stacktrace jlink
    - name: Execute jpackage
      run: ./gradlew --info --stacktrace jpackage
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: build/jpackage/*.dmg
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: build/jpackage/*.exe
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-msi
        path: build/jpackage/*.msi
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: build/jpackage/*.deb
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: build/jpackage/*.rpm
