# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: All Package

on:
  push:
    tags:
      - 'v*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    needs: release
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17.0.6'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2

    - run: gradle jlinkZip
    - run: gradle jpackage
    - run: gradle shadowJar

    - name: Upload ZIP as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-zip
        path: build/distributions/astre-image.zip
        retention-days: 4
    - name: Upload JAR as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-jar
        path: build/libs/*.jar
        retention-days: 4
    - name: Upload DMG as an artifact
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: build/jpackage/*.dmg
        retention-days: 4
    - name: Upload EXE as an artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: build/jpackage/*.exe
        retention-days: 4
    - name: Upload MSI as an artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-msi
        path: build/jpackage/*.msi
        retention-days: 4
    - name: Upload DEB as an artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: build/jpackage/*.deb
        retention-days: 4
    - name: Upload RPM as an artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: build/jpackage/*.rpm
        retention-days: 4
    - name: Upload PKG as an artifact
      if: matrix.os == 'macOS-latest'
      uses: actions/upload-artifact@v3
      with:
        name: astre-jdk${{ matrix.java }}-${{ matrix.os }}-pkg
        path: build/jpackage/*.pkg
        retention-days: 4
    - name: Upload /jpackage/ to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/jpackage/*.*

  release:
    runs-on: ubuntu-latest
    name: release

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Release notes for ${{ github.ref }}
        draft: false
        prerelease: false